[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_ENV = "development"
  NEXT_PUBLIC_APP_ENV = "demo"
  DATABASE_PROVIDER = "sqlite"
  SECURITY_ENHANCED = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  framework = "next"
  command = "npm run dev"
  port = 3000

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"