'use client';

import React, { useState, useEffect } from 'react';
import {
  Save,
  Plus,
  Trash2,
  Eye,
  Code,
  Settings,
  Type,
  Hash,
  Calendar,
  ToggleLeft,
  Image,
  List,
  Table,
  PenTool,
  ArrowLeft,
  CheckCircle,
  AlertTriangle,
  Copy,
  Download,
  Upload
} from 'lucide-react';

// ================================================================================
// INTERFACES
// ================================================================================

interface TemplatePlaceholder {
  id: string;
  key: string;
  label: string;
  type: 'text' | 'number' | 'date' | 'boolean' | 'image' | 'table' | 'list' | 'signature';
  required: boolean;
  defaultValue?: any;
  description?: string;
  validation?: {
    minLength?: number;
    maxLength?: number;
    pattern?: string;
    min?: number;
    max?: number;
  };
  formatting?: {
    dateFormat?: string;
    numberFormat?: string;
    currency?: string;
    style?: string;
  };
}

interface TemplateStyle {
  fonts: Array<{
    name: string;
    size: number;
    weight: string;
    style: string;
    color: string;
  }>;
  colors: {
    primary: string;
    secondary: string;
    accent: string;
    text: string;
    background: string;
  };
  spacing: {
    lineHeight: number;
    paragraphSpacing: number;
    marginTop: number;
    marginBottom: number;
    marginLeft: number;
    marginRight: number;
  };
  pageSettings: {
    size: 'A4' | 'A3' | 'Letter' | 'Legal';
    orientation: 'portrait' | 'landscape';
    margins: {
      top: number;
      bottom: number;
      left: number;
      right: number;
    };
    header?: string;
    footer?: string;
  };
}

interface DocumentTemplate {
  id?: string;
  name: string;
  category: string;
  description: string;
  templateType: 'pdf' | 'word' | 'html' | 'excel';
  templateContent: string;
  placeholders: TemplatePlaceholder[];
  styling: TemplateStyle;
  isActive: boolean;
  version: string;
}

interface TemplateEditorProps {
  template?: DocumentTemplate;
  onSave?: (template: DocumentTemplate) => void;
  onCancel?: () => void;
  readOnly?: boolean;
}

// ================================================================================
// DEFAULT VALUES
// ================================================================================

const DEFAULT_TEMPLATE: DocumentTemplate = {
  name: '',
  category: '',
  description: '',
  templateType: 'html',
  templateContent: `<!DOCTYPE html>
<html>
<head>
    <title>{{document_title}}</title>
    <meta charset="UTF-8">
</head>
<body>
    <div class="header">
        <h1>{{document_title}}</h1>
        <p>Generated on: {{generation_date}}</p>
    </div>
    
    <div class="content">
        <h2>Document Content</h2>
        <p>This is a sample template. Add your content here and use {{placeholders}} for dynamic data.</p>
        
        <p>Example: Hello {{user_name}}, welcome to {{company_name}}!</p>
    </div>
    
    <div class="footer">
        <p>Generated by PROP.ie Document System</p>
    </div>
</body>
</html>`,
  placeholders: [],
  styling: {
    fonts: [{
      name: 'Arial',
      size: 12,
      weight: 'normal',
      style: 'normal',
      color: '#000000'
    }],
    colors: {
      primary: '#3B82F6',
      secondary: '#6B7280',
      accent: '#10B981',
      text: '#111827',
      background: '#FFFFFF'
    },
    spacing: {
      lineHeight: 1.5,
      paragraphSpacing: 16,
      marginTop: 20,
      marginBottom: 20,
      marginLeft: 20,
      marginRight: 20
    },
    pageSettings: {
      size: 'A4',
      orientation: 'portrait',
      margins: {
        top: 25,
        bottom: 25,
        left: 25,
        right: 25
      }
    }
  },
  isActive: true,
  version: '1.0'
};

// ================================================================================
// MAIN COMPONENT
// ================================================================================

export default function TemplateEditor({
  template,
  onSave,
  onCancel,
  readOnly = false
}: TemplateEditorProps) {
  const [currentTemplate, setCurrentTemplate] = useState<DocumentTemplate>(
    template || DEFAULT_TEMPLATE
  );
  const [currentTab, setCurrentTab] = useState<'content' | 'placeholders' | 'styling' | 'preview'>('content');
  const [previewData, setPreviewData] = useState<{ [key: string]: any }>({});
  const [validationErrors, setValidationErrors] = useState<string[]>([]);

  // Initialize preview data when placeholders change
  useEffect(() => {
    const newPreviewData: { [key: string]: any } = {};
    currentTemplate.placeholders.forEach(placeholder => {
      newPreviewData[placeholder.key] = getSampleValue(placeholder);
    });
    setPreviewData(newPreviewData);
  }, [currentTemplate.placeholders]);

  // ================================================================================
  // PLACEHOLDER MANAGEMENT
  // ================================================================================

  const addPlaceholder = () => {
    const newPlaceholder: TemplatePlaceholder = {
      id: `placeholder_${Date.now()}`,
      key: '',
      label: '',
      type: 'text',
      required: false,
      description: ''
    };

    setCurrentTemplate(prev => ({
      ...prev,
      placeholders: [...prev.placeholders, newPlaceholder]
    }));
  };

  const updatePlaceholder = (id: string, updates: Partial<TemplatePlaceholder>) => {
    setCurrentTemplate(prev => ({
      ...prev,
      placeholders: prev.placeholders.map(placeholder =>
        placeholder.id === id ? { ...placeholder, ...updates } : placeholder
      )
    }));
  };

  const removePlaceholder = (id: string) => {
    setCurrentTemplate(prev => ({
      ...prev,
      placeholders: prev.placeholders.filter(placeholder => placeholder.id !== id)
    }));
  };

  const getSampleValue = (placeholder: TemplatePlaceholder): any => {
    switch (placeholder.type) {
      case 'text': return placeholder.defaultValue || 'Sample Text';
      case 'number': return placeholder.defaultValue || 42;
      case 'date': return placeholder.defaultValue || new Date().toISOString().split('T')[0];
      case 'boolean': return placeholder.defaultValue !== undefined ? placeholder.defaultValue : true;
      case 'list': return placeholder.defaultValue || ['Item 1', 'Item 2', 'Item 3'];
      case 'table': return placeholder.defaultValue || [
        { column1: 'Row 1 Col 1', column2: 'Row 1 Col 2' },
        { column1: 'Row 2 Col 1', column2: 'Row 2 Col 2' }
      ];
      case 'image': return placeholder.defaultValue || 'https://via.placeholder.com/150x100';
      case 'signature': return placeholder.defaultValue || 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==';
      default: return placeholder.defaultValue || '';
    }
  };

  // ================================================================================
  // VALIDATION
  // ================================================================================

  const validateTemplate = (): string[] => {
    const errors: string[] = [];

    if (!currentTemplate.name.trim()) {
      errors.push('Template name is required');
    }

    if (!currentTemplate.category.trim()) {
      errors.push('Template category is required');
    }

    if (!currentTemplate.templateContent.trim()) {
      errors.push('Template content is required');
    }

    // Validate placeholder keys are unique and valid
    const placeholderKeys = new Set<string>();
    currentTemplate.placeholders.forEach((placeholder, index) => {
      if (!placeholder.key.trim()) {
        errors.push(`Placeholder ${index + 1}: Key is required`);
      } else if (placeholderKeys.has(placeholder.key)) {
        errors.push(`Placeholder ${index + 1}: Key "${placeholder.key}" is duplicated`);
      } else if (!/^[a-zA-Z][a-zA-Z0-9_]*$/.test(placeholder.key)) {
        errors.push(`Placeholder ${index + 1}: Key "${placeholder.key}" is invalid (use letters, numbers, underscore only)`);
      }
      placeholderKeys.add(placeholder.key);

      if (!placeholder.label.trim()) {
        errors.push(`Placeholder ${index + 1}: Label is required`);
      }
    });

    return errors;
  };

  const handleSave = () => {
    const errors = validateTemplate();
    setValidationErrors(errors);

    if (errors.length === 0 && onSave) {
      onSave(currentTemplate);
    }
  };

  // ================================================================================
  // PREVIEW GENERATION
  // ================================================================================

  const generatePreview = (): string => {
    let content = currentTemplate.templateContent;

    // Replace placeholders with sample data
    currentTemplate.placeholders.forEach(placeholder => {
      const value = previewData[placeholder.key];
      const formattedValue = formatPreviewValue(value, placeholder);
      const regex = new RegExp(`{{\\s*${placeholder.key}\\s*}}`, 'g');
      content = content.replace(regex, formattedValue);
    });

    // Add styling if HTML
    if (currentTemplate.templateType === 'html') {
      const styles = generatePreviewCSS();
      if (content.includes('<head>')) {
        content = content.replace('<head>', `<head><style>${styles}</style>`);
      } else {
        content = `<style>${styles}</style>${content}`;
      }
    }

    return content;
  };

  const formatPreviewValue = (value: any, placeholder: TemplatePlaceholder): string => {
    if (value === null || value === undefined) return '';

    switch (placeholder.type) {
      case 'date':
        return new Date(value).toLocaleDateString();
      case 'boolean':
        return value ? 'Yes' : 'No';
      case 'list':
        return Array.isArray(value) ? `<ul>${value.map(item => `<li>${item}</li>`).join('')}</ul>` : String(value);
      case 'table':
        if (Array.isArray(value) && value.length > 0) {
          const headers = Object.keys(value[0]);
          return `<table border="1" style="border-collapse: collapse; width: 100%;">
            <thead><tr>${headers.map(h => `<th style="padding: 8px; background: #f5f5f5;">${h}</th>`).join('')}</tr></thead>
            <tbody>${value.map(row => `<tr>${headers.map(h => `<td style="padding: 8px;">${row[h] || ''}</td>`).join('')}</tr>`).join('')}</tbody>
          </table>`;
        }
        return String(value);
      case 'image':
        return `<img src="${value}" alt="Preview Image" style="max-width: 200px; height: auto;" />`;
      case 'signature':
        return `<img src="${value}" alt="Signature" style="max-width: 150px; height: auto;" />`;
      default:
        return String(value);
    }
  };

  const generatePreviewCSS = (): string => {
    const { fonts, colors, spacing } = currentTemplate.styling;
    return `
      body {
        font-family: ${fonts[0]?.name || 'Arial'}, sans-serif;
        font-size: ${fonts[0]?.size || 12}px;
        line-height: ${spacing.lineHeight};
        color: ${colors.text};
        background-color: ${colors.background};
        margin: ${spacing.marginTop}px ${spacing.marginRight}px ${spacing.marginBottom}px ${spacing.marginLeft}px;
      }
      h1, h2, h3 { color: ${colors.primary}; }
      a { color: ${colors.accent}; }
      .header, .footer { text-align: center; }
      table { margin: 10px 0; }
    `;
  };

  // ================================================================================
  // RENDER FUNCTIONS
  // ================================================================================

  const renderContentTab = () => (
    <div className="space-y-4">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Template Name</label>
          <input
            type="text"
            value={currentTemplate.name}
            onChange={(e) => setCurrentTemplate(prev => ({ ...prev, name: e.target.value }))}
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            placeholder="Enter template name"
            disabled={readOnly}
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Category</label>
          <input
            type="text"
            value={currentTemplate.category}
            onChange={(e) => setCurrentTemplate(prev => ({ ...prev, category: e.target.value }))}
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            placeholder="e.g., Legal Documents, Reports"
            disabled={readOnly}
          />
        </div>
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">Description</label>
        <textarea
          value={currentTemplate.description}
          onChange={(e) => setCurrentTemplate(prev => ({ ...prev, description: e.target.value }))}
          className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          rows={2}
          placeholder="Describe what this template is used for"
          disabled={readOnly}
        />
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">Template Type</label>
        <select
          value={currentTemplate.templateType}
          onChange={(e) => setCurrentTemplate(prev => ({ ...prev, templateType: e.target.value as any }))}
          className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          disabled={readOnly}
        >
          <option value="html">HTML</option>
          <option value="pdf">PDF</option>
          <option value="word">Word</option>
          <option value="excel">Excel</option>
        </select>
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">Template Content</label>
        <textarea
          value={currentTemplate.templateContent}
          onChange={(e) => setCurrentTemplate(prev => ({ ...prev, templateContent: e.target.value }))}
          className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent font-mono text-sm"
          rows={15}
          placeholder="Enter your template content here. Use {{placeholder_name}} for dynamic content."
          disabled={readOnly}
        />
        <p className="text-xs text-gray-500 mt-1">
          Use double curly braces for placeholders: {"{{placeholder_name}}"}
        </p>
      </div>
    </div>
  );

  const renderPlaceholdersTab = () => (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h4 className="font-medium text-gray-900">Template Placeholders</h4>
        {!readOnly && (
          <button
            onClick={addPlaceholder}
            className="flex items-center gap-2 px-3 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
          >
            <Plus className="w-4 h-4" />
            Add Placeholder
          </button>
        )}
      </div>

      <div className="space-y-4">
        {currentTemplate.placeholders.map((placeholder) => (
          <div key={placeholder.id} className="bg-gray-50 p-4 rounded-lg border">
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Key</label>
                <input
                  type="text"
                  value={placeholder.key}
                  onChange={(e) => updatePlaceholder(placeholder.id, { key: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  placeholder="placeholder_key"
                  disabled={readOnly}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Label</label>
                <input
                  type="text"
                  value={placeholder.label}
                  onChange={(e) => updatePlaceholder(placeholder.id, { label: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  placeholder="Display Label"
                  disabled={readOnly}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Type</label>
                <select
                  value={placeholder.type}
                  onChange={(e) => updatePlaceholder(placeholder.id, { type: e.target.value as any })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  disabled={readOnly}
                >
                  <option value="text">Text</option>
                  <option value="number">Number</option>
                  <option value="date">Date</option>
                  <option value="boolean">Boolean</option>
                  <option value="list">List</option>
                  <option value="table">Table</option>
                  <option value="image">Image</option>
                  <option value="signature">Signature</option>
                </select>
              </div>
              <div className="flex items-end justify-between">
                <div className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    checked={placeholder.required}
                    onChange={(e) => updatePlaceholder(placeholder.id, { required: e.target.checked })}
                    disabled={readOnly}
                  />
                  <label className="text-sm text-gray-700">Required</label>
                </div>
                {!readOnly && (
                  <button
                    onClick={() => removePlaceholder(placeholder.id)}
                    className="p-2 text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                )}
              </div>
            </div>
            
            <div className="mt-3">
              <label className="block text-sm font-medium text-gray-700 mb-1">Description</label>
              <input
                type="text"
                value={placeholder.description || ''}
                onChange={(e) => updatePlaceholder(placeholder.id, { description: e.target.value })}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                placeholder="Optional description for this field"
                disabled={readOnly}
              />
            </div>
          </div>
        ))}
      </div>

      {currentTemplate.placeholders.length === 0 && (
        <div className="text-center py-8">
          <Type className="w-12 h-12 mx-auto text-gray-400" />
          <p className="text-gray-600 mt-2">No placeholders defined</p>
          <p className="text-sm text-gray-500">Add placeholders to make your template dynamic</p>
        </div>
      )}
    </div>
  );

  const renderStylingTab = () => (
    <div className="space-y-6">
      {/* Colors */}
      <div>
        <h4 className="font-medium text-gray-900 mb-4">Colors</h4>
        <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
          {Object.entries(currentTemplate.styling.colors).map(([key, value]) => (
            <div key={key}>
              <label className="block text-sm font-medium text-gray-700 mb-1 capitalize">{key}</label>
              <input
                type="color"
                value={value}
                onChange={(e) => setCurrentTemplate(prev => ({
                  ...prev,
                  styling: {
                    ...prev.styling,
                    colors: { ...prev.styling.colors, [key]: e.target.value }
                  }
                }))}
                className="w-full h-10 border border-gray-300 rounded-lg"
                disabled={readOnly}
              />
            </div>
          ))}
        </div>
      </div>

      {/* Typography */}
      <div>
        <h4 className="font-medium text-gray-900 mb-4">Typography</h4>
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Font Family</label>
            <select
              value={currentTemplate.styling.fonts[0]?.name || 'Arial'}
              onChange={(e) => setCurrentTemplate(prev => ({
                ...prev,
                styling: {
                  ...prev.styling,
                  fonts: [{ ...prev.styling.fonts[0], name: e.target.value }]
                }
              }))}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              disabled={readOnly}
            >
              <option value="Arial">Arial</option>
              <option value="Times New Roman">Times New Roman</option>
              <option value="Helvetica">Helvetica</option>
              <option value="Georgia">Georgia</option>
              <option value="Verdana">Verdana</option>
            </select>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Font Size</label>
            <input
              type="number"
              value={currentTemplate.styling.fonts[0]?.size || 12}
              onChange={(e) => setCurrentTemplate(prev => ({
                ...prev,
                styling: {
                  ...prev.styling,
                  fonts: [{ ...prev.styling.fonts[0], size: parseInt(e.target.value) }]
                }
              }))}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              min="8"
              max="72"
              disabled={readOnly}
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Line Height</label>
            <input
              type="number"
              step="0.1"
              value={currentTemplate.styling.spacing.lineHeight}
              onChange={(e) => setCurrentTemplate(prev => ({
                ...prev,
                styling: {
                  ...prev.styling,
                  spacing: { ...prev.styling.spacing, lineHeight: parseFloat(e.target.value) }
                }
              }))}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              min="1"
              max="3"
              disabled={readOnly}
            />
          </div>
        </div>
      </div>

      {/* Page Settings */}
      <div>
        <h4 className="font-medium text-gray-900 mb-4">Page Settings</h4>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Page Size</label>
            <select
              value={currentTemplate.styling.pageSettings.size}
              onChange={(e) => setCurrentTemplate(prev => ({
                ...prev,
                styling: {
                  ...prev.styling,
                  pageSettings: { ...prev.styling.pageSettings, size: e.target.value as any }
                }
              }))}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              disabled={readOnly}
            >
              <option value="A4">A4</option>
              <option value="A3">A3</option>
              <option value="Letter">Letter</option>
              <option value="Legal">Legal</option>
            </select>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Orientation</label>
            <select
              value={currentTemplate.styling.pageSettings.orientation}
              onChange={(e) => setCurrentTemplate(prev => ({
                ...prev,
                styling: {
                  ...prev.styling,
                  pageSettings: { ...prev.styling.pageSettings, orientation: e.target.value as any }
                }
              }))}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              disabled={readOnly}
            >
              <option value="portrait">Portrait</option>
              <option value="landscape">Landscape</option>
            </select>
          </div>
        </div>

        {/* Margins */}
        <div className="mt-4">
          <label className="block text-sm font-medium text-gray-700 mb-2">Margins (mm)</label>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {['top', 'bottom', 'left', 'right'].map(margin => (
              <div key={margin}>
                <label className="block text-xs text-gray-600 mb-1 capitalize">{margin}</label>
                <input
                  type="number"
                  value={(currentTemplate.styling.pageSettings.margins as any)[margin]}
                  onChange={(e) => setCurrentTemplate(prev => ({
                    ...prev,
                    styling: {
                      ...prev.styling,
                      pageSettings: {
                        ...prev.styling.pageSettings,
                        margins: {
                          ...prev.styling.pageSettings.margins,
                          [margin]: parseInt(e.target.value)
                        }
                      }
                    }
                  }))}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  min="0"
                  max="100"
                  disabled={readOnly}
                />
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );

  const renderPreviewTab = () => (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h4 className="font-medium text-gray-900">Template Preview</h4>
        <div className="flex items-center gap-2">
          <button
            onClick={() => {
              const previewContent = generatePreview();
              const blob = new Blob([previewContent], { type: 'text/html' });
              const url = URL.createObjectURL(blob);
              window.open(url, '_blank');
            }}
            className="flex items-center gap-2 px-3 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
          >
            <Eye className="w-4 h-4" />
            Open in New Tab
          </button>
        </div>
      </div>

      <div className="border border-gray-300 rounded-lg overflow-hidden">
        <div
          className="w-full h-96 overflow-auto bg-white p-4"
          dangerouslySetInnerHTML={{ __html: generatePreview() }}
        />
      </div>

      {/* Preview Data Controls */}
      {currentTemplate.placeholders.length > 0 && (
        <div className="bg-gray-50 p-4 rounded-lg">
          <h5 className="font-medium text-gray-900 mb-3">Preview Data</h5>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {currentTemplate.placeholders.map(placeholder => (
              <div key={placeholder.id}>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  {placeholder.label}
                </label>
                <input
                  type="text"
                  value={previewData[placeholder.key] || ''}
                  onChange={(e) => setPreviewData(prev => ({ ...prev, [placeholder.key]: e.target.value }))}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  placeholder={`Sample ${placeholder.label.toLowerCase()}`}
                />
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );

  // ================================================================================
  // MAIN RENDER
  // ================================================================================

  return (
    <div className="max-w-7xl mx-auto bg-white">
      {/* Header */}
      <div className="border-b border-gray-200 bg-white sticky top-0 z-10">
        <div className="px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              {onCancel && (
                <button
                  onClick={onCancel}
                  className="flex items-center gap-2 text-gray-600 hover:text-gray-900"
                >
                  <ArrowLeft className="w-4 h-4" />
                  Back
                </button>
              )}
              <div>
                <h1 className="text-2xl font-bold text-gray-900">
                  {template ? 'Edit Template' : 'Create Template'}
                </h1>
                <p className="text-gray-600">
                  {readOnly ? 'View template details' : 'Design and configure your document template'}
                </p>
              </div>
            </div>
            <div className="flex items-center gap-3">
              {!readOnly && (
                <button
                  onClick={handleSave}
                  className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
                >
                  <Save className="w-4 h-4" />
                  Save Template
                </button>
              )}
            </div>
          </div>

          {/* Validation Errors */}
          {validationErrors.length > 0 && (
            <div className="mt-4 p-4 bg-red-50 border border-red-200 rounded-lg">
              <div className="flex items-center gap-2 text-red-800 mb-2">
                <AlertTriangle className="w-4 h-4" />
                <span className="font-medium">Please fix the following errors:</span>
              </div>
              <ul className="list-disc list-inside text-sm text-red-700 space-y-1">
                {validationErrors.map((error, index) => (
                  <li key={index}>{error}</li>
                ))}
              </ul>
            </div>
          )}

          {/* Tabs */}
          <div className="flex items-center gap-1 mt-4">
            {[
              { id: 'content', label: 'Content', icon: <Code className="w-4 h-4" /> },
              { id: 'placeholders', label: 'Placeholders', icon: <Type className="w-4 h-4" /> },
              { id: 'styling', label: 'Styling', icon: <Settings className="w-4 h-4" /> },
              { id: 'preview', label: 'Preview', icon: <Eye className="w-4 h-4" /> }
            ].map(tab => (
              <button
                key={tab.id}
                onClick={() => setCurrentTab(tab.id as any)}
                className={`flex items-center gap-2 px-4 py-2 rounded-lg transition-colors ${
                  currentTab === tab.id
                    ? 'bg-blue-100 text-blue-700 border border-blue-200'
                    : 'text-gray-600 hover:text-gray-900 hover:bg-gray-50'
                }`}
              >
                {tab.icon}
                {tab.label}
              </button>
            ))}
          </div>
        </div>
      </div>

      <div className="p-6">
        {currentTab === 'content' && renderContentTab()}
        {currentTab === 'placeholders' && renderPlaceholdersTab()}
        {currentTab === 'styling' && renderStylingTab()}
        {currentTab === 'preview' && renderPreviewTab()}
      </div>
    </div>
  );
}